### ISSUE TITLE
Bug: Seeder Broke in version 2.5.0

### ISSUE THREAD

**Issue by tal1992** [tada5hi/typeorm-extension#538]
### Versions
- Node: 18
- OS: MAC OS
- Version: Latest (was working fine with v2.4.1)

### Steps to reproduce 

import { DataSource } from 'typeorm';
import {createDatabase, runSeeders, SeederOptions} from 'typeorm-extension';

...
<-- fetch datasource from seeder file and pass in function like below -->

```js
try {
  await runSeeders(datasource);
}
```

### What is Expected?
Should seed the tables with data

### What is actually happening?
TypeError: clazz.run is not a function\n    at runSeeder
typeorm-extension/dist/seeder/module.js:97:18

_Please note that the seeding was working fine with 2.4.1 and suddenly after the update to latest version, it has started throwing the error. I have not changed anything in the seed file._

Update - This is possibly due to this Change of Lazy transpiling of seeder (https://github.com/tada5hi/typeorm-extension/commit/5d092ad9ed8e83f2c53a82c67b7b9e907a9a3e0a)

**Comment by tada5hi** [comment]
Can you provide a repo/code snippet for reproduction ?

**Comment by tada5hi** [comment]
@tal1992 is your seeder class a named oder default export?

**Comment by tal1992** [comment]
```ts
import {Seeder} from 'typeorm-extension';
import {DataSource} from 'typeorm';
import {myEntity} from '../entity/MyEntity;
import {mySeedData} from '../data/MySeedData.seed';

export default class MySeeder implements Seeder {
  public async run(dataSource: DataSource): Promise<void> {
	// some business logic
	repository.insert(my data);

  }
}
```

**Comment by tada5hi** [comment]
> @tada5hi it looks like this -
> 
> ```ts
> import {Seeder} from 'typeorm-extension';
> import {DataSource} from 'typeorm';
> import {myEntity} from '../entity/MyEntity;
> import {mySeedData} from '../data/MySeedData.seed';
> 
> export default class MySeeder implements Seeder {
>   public async run(dataSource: DataSource): Promise<void> {
> 	// some business logic
> 	repository.insert(mydata);
> 
>   }
> }
> ```

A repo for repoduction would be realy great, since i unfortunately can not replicate the error :pensive:
